[package]
name = "fmtbuf"
version = "0.2.0"
edition = "2021"
rust-version = "1.81"
authors = ["Travis Gockel <travis@gockelhut.com>"]
license = "Apache-2.0"
description = "Utilities for formatting to a fixed-size buffer"
keywords = ["buffer", "truncation", "utf-8", "ffi", "no-std"]
categories = ["development-tools::ffi", "no-std"]
readme = "README.md"
repository = "https://github.com/tgockel/fmtbuf"

[features]
default = ["std"]
std = []

[dependencies]

[dev-dependencies]
clap = { version = "4.0.0", features = ["derive"] }

[badges]
maintenance = { status = "experimental" } # this line is currently experimental

[lints.rust]
missing_docs = "deny"
unsafe_op_in_unsafe_fn = "deny"
unreachable_pub = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
